const origListeners = __.DEBUG && new WeakMap();

if (__.MV3) {
  global.browser = chrome;
  if (__.DEBUG) addEventLogger();
} else if (!__.B_FIREFOX && !global.browser?.runtime) {
  /* Auto-promisifier with a fallback to direct call on signature error.
     The fallback isn't used now since we call all synchronous methods via `chrome` */
  const directEvents = ['addListener', 'removeListener', 'hasListener', 'hasListeners'];
  // generated by tools/chrome-api-no-cb.js
  const directMethods = {
    alarms: ['create'],
    extension: ['getBackgroundPage', 'getExtensionTabs', 'getURL', 'getViews', 'setUpdateUrlData'],
    i18n: ['getMessage', 'getUILanguage'],
    identity: ['getRedirectURL'],
    runtime: ['connect', 'connectNative', 'getManifest', 'getURL', 'reload', 'restart'],
    tabs: ['connect'],
  };
  const promisify = function (fn, ...args) {
    let resolve, reject;
    // Saving the local callstack before making an async call
    const localErr = new Error();
    fn.call(this, ...args, (...results) => {
      const {lastError} = chrome.runtime;
      if (lastError) {
        localErr.message = lastError.message;
        reject(localErr);
      } else {
        /* Some callbacks have 2 parameters so we're resolving as an array in that case.
           For example, chrome.runtime.requestUpdateCheck and chrome.webRequest.onAuthRequired */
        resolve(results.length <= 1 ? results[0] : results);
      }
    });
    return new Promise((ok, ko) => {
      resolve = ok;
      reject = ko;
    });
  };
  const proxyHandler = {
    get({src, name}, key, instance) {
      let res = src[key];
      if (key.startsWith('on')) {
        // We only use listener methods in an event object, copying it as-is
      } else if (res && typeof res === 'object') {
        res = createProxy(res, key);
      } else if (typeof res === 'function' && key.endsWith('Listener') && __.DEBUG) {
        res = patchEventListener(src, key, res);
      } else if (typeof res === 'function') {
        res = (name.startsWith('on') ? directEvents : directMethods[name] || []).includes(key)
          ? res.bind(src)
          : promisify.bind(src, res);
      }
      instance[key] = res;
      return res;
    },
  };
  const createProxy = (src, name = '') => Object.create(new Proxy({src, name}, proxyHandler));
  global.browser = createProxy(chrome);
} else if (__.DEBUG) {
  addEventLogger();
}

function addEventLogger() {
  const patched = new WeakSet();
  const handler = {
    get(obj, k, instance) {
      let val = obj[k];
      if (val && typeof val === 'object' && !patched.has(val)) {
        patched.add(val);
        let hasEvents, evt, fn;
        for (k in val) {
          if (k.startsWith('on') && (evt = val[k]) && typeof evt === 'object') {
            for (const ke in evt) {
              if (ke.endsWith('Listener') && typeof (fn = evt[ke]) === 'function') {
                evt[ke] = patchEventListener(evt, k, fn);
              }
            }
            hasEvents = true;
          }
        }
        if (!hasEvents) val = Object.create(new Proxy(val, handler));
      }
      instance[k] = val;
      return val;
    },
  };
  const patchedChrome = global.chrome = Object.create(new Proxy(chrome, handler));
  global.browser = chrome === browser
    ? patchedChrome
    : Object.create(new Proxy(browser, handler));
}

function patchEventListener(obj, name, fn) {
  let res = fn;
  switch (fn.name) {
    case 'addListener':
      res = (cb, ...opts) =>
        fn.call(obj, (...args) => {
          console.log('%c%s', 'color:#A2C;font-weight:bold', name,
            ...name === 'onMessage' ? args.slice(0, 2) : args);
          return cb(...args);
        }, ...opts);
      origListeners.set(fn, res);
      break;
    case 'removeListener':
      res = cb => {
        fn.call(obj, origListeners.get(cb));
        origListeners.delete(cb);
      };
      break;
    case 'hasListener':
      res = cb => fn.call(obj, origListeners.get(cb));
      break;
  }
  return res;
}
