const uad = navigator.userAgentData;
const ua = uad || navigator.userAgent;
const brands = uad ? uad.brands.map(_ => `${_.brand}/${_.version}`).join(' ') : ua;
const platform = uad ? uad.platform : ua;
const chromeVer = +brands.match(/Chrom\w*\/(\d+)|$/)[1];
export const CHROME = chromeVer;
export const FIREFOX = chromeVer ? NaN : +brands.match(/Firefox\w*\/(\d+)|$/)[1];
export const OPERA = +brands.match(/(Opera|OPR)\w*\/(\d+)|$/)[1];
export const MAC = /mac/i.test(platform);
export const MOBILE = uad ? uad.mobile : /Android/.test(ua);
export const WINDOWS = /Windows/.test(platform);
export const VIVALDI = +brands.match(/Vivaldi\w*\/(\d+)|$/)[1];
