name: "submit"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm zip
      - name: Browser Plugin Publish
        uses: plasmo-corp/bpp@v1
        with:
          artifact: ./stylus.zip
          keys: ${{ secrets.SUBMIT_KEYS }}
